import { initRadarMap, updateRadarMap, centerRadarMap } from './map.js';

const $=id=>document.getElementById(id),TOKEN_KEY='radar_token',PROFILE_KEY='radar_profile',SHIFT_KEY='radar_shift',ONBOARD_KEY='radar_onboard_v1',GOALS_KEY='radar_goals_v1';
let offers=[],statsData=null,clusters=[],position=null,network={personal:[],market:[],networkCoverage:'learning'},heartbeat=null,onboardStep=0,riderSettings={target_dph:35,speed_low_mph:12,speed_mid_mph:16,speed_high_mph:20,active_speed_level:'high',service_overhead_minutes:4.5,vehicle:'ebike'};
const defaults={vehicle:'ebike',target:35,radius:2.5};const goalDefaults={daily:175,blocks:{BREAKFAST:35,LUNCH:45,AFTERNOON:0,DINNER:70,LATE:25,'OFF-PEAK':0}};const goals=()=>{try{return {...goalDefaults,...JSON.parse(localStorage.getItem(GOALS_KEY)||'{}'),blocks:{...goalDefaults.blocks,...(JSON.parse(localStorage.getItem(GOALS_KEY)||'{}').blocks||{})}}}catch{return goalDefaults}};
const profile=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}}catch{return {...defaults}}};
const saveProfile=p=>localStorage.setItem(PROFILE_KEY,JSON.stringify({...profile(),...p}));
const token=()=>localStorage.getItem(TOKEN_KEY)||'';
const shift=()=>{try{return JSON.parse(localStorage.getItem(SHIFT_KEY)||'null')}catch{return null}};
const saveShift=v=>v?localStorage.setItem(SHIFT_KEY,JSON.stringify(v)):localStorage.removeItem(SHIFT_KEY);
const headers=()=>({'Content-Type':'application/json','x-capture-token':token()});
const money=n=>n==null?'—':`$${Number(n).toFixed(2)}`;
const minsSince=iso=>Math.max(0,(Date.now()-new Date(iso).getTime())/60000);
function blockFor(d=new Date()){const h=d.getHours()+d.getMinutes()/60;if(h>=6&&h<10.5)return'BREAKFAST';if(h>=10.5&&h<14.5)return'LUNCH';if(h>=14.5&&h<16.5)return'AFTERNOON';if(h>=16.5&&h<21)return'DINNER';if(h>=21||h<1)return'LATE';return'OFF-PEAK'}
async function api(path,opt={}){if(!token())throw new Error('Set your capture token first.');const r=await fetch(path,{...opt,headers:{...headers(),...(opt.headers||{})}}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function getLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location unavailable'));navigator.geolocation.getCurrentPosition(p=>{position={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};resolve(position)},reject,{enableHighAccuracy:true,maximumAge:45000,timeout:8000})})}
async function pingPresence(event='heartbeat'){if(!shift()||!token())return;try{const p=await getLocation();await api('/api/presence',{method:'POST',body:JSON.stringify({...p,event,vehicle:profile().vehicle})});}catch{}}
function isOfferSignal(o){if(!o)return false;if(Number(o.payout)>0||Number(o.miles)>0||Number(o.eta_minutes)>0)return true;const t=String(o.raw_text||'').toLowerCase();return /(guaranteed|incl\. tip|includes expected tip|delivery|shop & deliver|add a delivery|accept request|\baccept\b)/.test(t)}
function signalOffers(){return offers.filter(isOfferSignal)}
function recent(minutes=60){const cut=Date.now()-minutes*60000;return signalOffers().filter(o=>new Date(o.captured_at).getTime()>=cut)}
function effectiveDph(o){if(!(Number(o?.payout)>0))return null;const eta=Number(o.radar_eta_minutes)||Number(o.eta_minutes)||((Number(o.miles)||0)/Math.max(3,Number(riderSettings.speed_high_mph)||20)*60+Number(riderSettings.service_overhead_minutes||4.5)),shop=o.is_shop?Math.max(8,Math.min(25,(Number(o.item_count)||6)*1.2)):0;return Number(o.payout)/Math.max(1,eta+shop)*60}
function median(arr){const a=arr.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function allCells(){return [...(network.market?.length?network.market:network.personal||[])]}function bestCell(){return allCells().sort((a,b)=>(b.properties?.score||0)-(a.properties?.score||0))[0]||null}function heatForCell(cell){return allCells().find(f=>f.properties?.cell===cell)?.properties?.heat||null}
function recommendation(){const s=shift(),p=profile();if(!s)return{advice:'START A SHIFT',reason:'Radar needs online exposure and captured offers before it can estimate opportunity.',radius:`${p.radius.toFixed(1)} mi`,confidence:'LEARNING'};const last=signalOffers()[0],idle=last?minsSince(last.captured_at):minsSince(s.startedAt),best=bestCell(),conf=best?.properties?.confidence||0;if(idle<8)return{advice:'STAY',reason:`Fresh offer ${Math.round(idle)}m ago. Keep the tight ${p.vehicle} radius while flow is alive.`,radius:`${p.radius.toFixed(1)} mi`,confidence:conf>.6?'HIGH':'LEARNING'};if(idle<15)return{advice:'WIDEN',reason:`${Math.round(idle)} idle minutes. Allow a slightly longer order only if its effective rate still clears your target.`,radius:`${Math.max(p.radius,3.5).toFixed(1)} mi`,confidence:conf>.45?'MED':'LEARNING'};if(best)return{advice:`MOVE → ${(best.properties.label||'BEST CELL').toUpperCase()}`,reason:`${Math.round(idle)} idle minutes. Best learned area is ${best.properties.heat||'LEARNING'} with ${best.properties.offersPerOnlineHour??'—'} observed offers/hr.`,radius:'4–5 mi escape',confidence:conf>.65?'HIGH':'MED'};return{advice:'ESCAPE MODE',reason:`${Math.round(idle)} idle minutes. Relocate once toward dense merchants or accept a longer order only when it improves your next position.`,radius:'4–5 mi escape',confidence:'LEARNING'};}
async function refreshData(){if(!token()){render();return;}try{const s=await api('/api/settings');riderSettings={...riderSettings,...(s.settings||{})};saveProfile({target:Number(riderSettings.target_dph||35),vehicle:riderSettings.vehicle||profile().vehicle});renderRiderSettings();const p=profile();const[f,n,st,cl]=await Promise.all([api('/api/feed?hours=168'),api(`/api/network?hours=168&vehicle=${encodeURIComponent(p.vehicle)}&target=${Number(riderSettings.target_dph||p.target)}`),api('/api/stats'),api('/api/clusters')]);offers=f.offers||[];network=n||network;statsData=st;clusters=cl.clusters||[];if(st?.activeShift)saveShift({startedAt:st.activeShift.started_at});else if(shift())saveShift(null);}catch(e){console.warn(e)}render();renderStats();renderMap();}
async function renderMap(){try{await initRadarMap();const shared=network.market?.length?network.market:null,base=shared||network.personal||[],clusterByCell=new Map(clusters.map(x=>[x.properties?.cell,x.properties])),features=base.map(f=>({...f,properties:{...f.properties,...(clusterByCell.get(f.properties?.cell)||{})}}));for(const cl of clusters){if(!features.some(f=>f.properties?.cell===cl.properties?.cell))features.push(cl)};const last=signalOffers()[0],destination=last?.dropoff_lat!=null&&last?.dropoff_lng!=null?{lat:Number(last.dropoff_lat),lng:Number(last.dropoff_lng),zone:last.dropoff_zone}:null;await updateRadarMap({features,position,destination,history:statsData?.recentEvents||[],fit:false});$('networkBadge').textContent=shared?'NETWORK':'PERSONAL';$('networkBadge').classList.toggle('live',Boolean(shared));$('mapStatus').textContent=features.length?`${features.length} learned restaurant-flow cell${features.length===1?'':'s'} · HOT/WARM/COOL/DEAD is based on observed offer flow, payout quality, recency, and confidence.`:'Capture offers while online. Unknown Uber supply is inferred from the market response you observe: offers per online exposure-hour.';}catch(e){$('mapStatus').textContent=`Map unavailable: ${e.message}`}}
function render(){const s=shift(),p=profile(),rec=recommendation(),last=signalOffers()[0];if(!last&&$('lastDestination'))$('lastDestination').textContent='Destination unknown';$('blockBadge').textContent=s?blockFor():'OFF';$('blockBadge').classList.toggle('live',!!s);$('advice').textContent=rec.advice;$('reason').textContent=rec.reason;$('radius').textContent=rec.radius;$('confidence').textContent=rec.confidence;$('targetMetric').textContent=`$${p.target}`;$('zone').textContent=last?.zone||'—';const idle=s?(last?minsSince(last.captured_at):minsSince(s.startedAt)):null;$('idle').textContent=idle==null?'—':`${Math.round(idle)}m`;const r=recent(60);$('pingsHr').textContent=r.length?r.length.toFixed(1):'—';const md=median(r.map(effectiveDph));$('offerDph').textContent=md?`$${Math.round(md)}`:'—';const decisions=signalOffers().filter(o=>['accepted','completed','delivered','rejected'].includes(o.state)),taken=decisions.filter(o=>['accepted','completed','delivered'].includes(o.state)).length;$('takeRate').textContent=decisions.length?`${Math.round(taken/decisions.length*100)}%`:'—';if(last){$('lastMerchant').textContent=last.merchant||'Unknown merchant';$('lastPay').textContent=money(last.payout);$('lastMiles').textContent=last.miles?`${Number(last.miles).toFixed(1)} mi`:'—';$('lastEta').textContent=last.radar_eta_minutes?`${Math.round(Number(last.radar_eta_minutes))}m Radar`:last.eta_minutes?`${last.eta_minutes}m Uber`:'—';const dropHeat=heatForCell(last.dropoff_market_cell);$('lastDestination').textContent=last.dropoff_zone?`→ ${last.dropoff_zone}${dropHeat?` · ${dropHeat}`:''}`:last.dropoff_text?`Destination hint: ${last.dropoff_text}`:'Destination unknown';const d=effectiveDph(last),idleNow=s?(last?minsSince(last.captured_at):minsSince(s.startedAt)):0,mode=idleNow>=15?'escape':idleNow>=8?'slow':'normal',factor=mode==='escape'?.62:mode==='slow'?.72:.80,borderFactor=Math.max(.50,factor-.10),v=d>=p.target*factor?'TAKE':d>=p.target*borderFactor?'BORDERLINE':'SKIP';$('lastVerdict').textContent=d?`${v} · $${Math.round(d)}/h`:v;$('lastVerdict').className=`pill ${v.toLowerCase()}`}$('shiftBtn').textContent=s?'END':'START';$('token').value=token();updateClock();}
function renderLiveGoals(){const g=goals(),block=blockFor(),dayEarned=Number(statsData?.todayEarnings??statsData?.shiftEarnings??0),blockEarned=Number(statsData?.blockEarnings??0),dayGoal=Number(g.daily||0),blockGoal=Number(g.blocks?.[block]||0);if($('todayEarned'))$('todayEarned').textContent=money(dayEarned);if($('dailyGoal'))$('dailyGoal').textContent=money(dayGoal);if($('dailyGoalBar'))$('dailyGoalBar').style.width=`${Math.min(100,dayGoal?dayEarned/dayGoal*100:0)}%`;if($('liveBlockName'))$('liveBlockName').textContent=block;if($('blockEarned'))$('blockEarned').textContent=money(blockEarned);if($('blockGoal'))$('blockGoal').textContent=money(blockGoal);if($('blockGoalBar'))$('blockGoalBar').style.width=`${Math.min(100,blockGoal?blockEarned/blockGoal*100:0)}%`;}
function renderStats(){if(!statsData)return;const goal=Number(statsData.monthlyGoal||4000),earned=Number(statsData.totalEarnings||0),pct=Math.max(0,Math.min(100,earned/goal*100));if($('goalTitle'))$('goalTitle').textContent=`${goal.toLocaleString()} monthly goal`;if($('goalPct'))$('goalPct').textContent=`${Math.round(pct)}%`;if($('goalBar'))$('goalBar').style.width=`${pct}%`;if($('actualEarnings'))$('actualEarnings').textContent=money(earned);if($('onlineRate'))$('onlineRate').textContent=`${Number(statsData.onlineDph||0).toFixed(0)}`;if($('moneyRateMirror'))$('moneyRateMirror').textContent=`${Number(statsData.onlineDph||0).toFixed(0)}`;if($('completedCount'))$('completedCount').textContent=statsData.completed||0;if($('trueIdle'))$('trueIdle').textContent=statsData.activeShift?`${Math.round(statsData.idleMinutes||0)}m`:'—';if($('blockOffers'))$('blockOffers').textContent=statsData.offers||0;if($('blockZone'))$('blockZone').textContent=statsData.recentEvents?.at(-1)?.zone||signalOffers()[0]?.zone||'—';if($('blockTitle'))$('blockTitle').textContent=statsData.activeShift?`${blockFor()} · LIVE`:'Not working';if($('paceText')){const hours=Number(statsData.onlineMinutes||0)/60;$('paceText').textContent=hours?`${hours.toFixed(1)} online hours tracked · ${money(Math.max(0,goal-earned))} remaining toward goal.`:'Start a shift to build your earnings pace.'}if($('merchantStats')){$('merchantStats').innerHTML=(statsData.merchantStats||[]).slice(0,6).map(m=>`<div class="merchant-row"><b>${m.merchant}</b><span>${m.offers} offers · ${m.completed} done · ${m.avgWaitMinutes==null?'wait learning':m.avgWaitMinutes+'m avg wait'}</span></div>`).join('')||'<p class="hint">Complete deliveries to build restaurant stats.</p>'}renderLiveGoals();updateServerClock()}
function updateServerClock(){if(!$('serverShiftClock'))return;const s=statsData?.activeShift;if(!s){$('serverShiftClock').textContent='0:00';return}const sec=Math.max(0,Math.floor((Date.now()-new Date(s.started_at))/1000)),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60);$('serverShiftClock').textContent=`${h}:${String(m).padStart(2,'0')}`}
function renderRiderSettings(){if(!$('speedLow'))return;$('speedLow').value=Number(riderSettings.speed_low_mph||12);$('speedMid').value=Number(riderSettings.speed_mid_mph||16);$('speedHigh').value=Number(riderSettings.speed_high_mph||20);$('serviceOverhead').value=Number(riderSettings.service_overhead_minutes??4.5);$('profileTarget').value=Number(riderSettings.target_dph||35);$('activeSpeedBadge').textContent=String(riderSettings.active_speed_level||'high').toUpperCase();document.querySelectorAll('[data-speed-level]').forEach(b=>b.classList.toggle('selected',b.dataset.speedLevel===riderSettings.active_speed_level));}
async function saveRiderSettings(overrides={}){const payload={vehicle:profile().vehicle,target_dph:Number($('profileTarget')?.value||riderSettings.target_dph||35),speed_low_mph:Number($('speedLow')?.value||riderSettings.speed_low_mph||12),speed_mid_mph:Number($('speedMid')?.value||riderSettings.speed_mid_mph||16),speed_high_mph:Number($('speedHigh')?.value||riderSettings.speed_high_mph||20),active_speed_level:overrides.active_speed_level||riderSettings.active_speed_level||'high',service_overhead_minutes:Number($('serviceOverhead')?.value??riderSettings.service_overhead_minutes??4.5)};const out=await api('/api/settings',{method:'POST',body:JSON.stringify(payload)});riderSettings={...riderSettings,...(out.settings||payload)};saveProfile({target:Number(riderSettings.target_dph||35),vehicle:riderSettings.vehicle||profile().vehicle});renderRiderSettings();render();return riderSettings;}
async function mark(state){try{await api('/api/action',{method:'POST',body:JSON.stringify({state})});await refreshData()}catch(e){alert(e.message)}}
async function toggleShift(){if(shift()){await api('/api/shift',{method:'POST',body:JSON.stringify({action:'end'})}).catch(()=>null);await pingPresence('shift_end');saveShift(null);if(heartbeat)clearInterval(heartbeat);heartbeat=null;render();return}const startedAt=new Date().toISOString();saveShift({startedAt});await api('/api/shift',{method:'POST',body:JSON.stringify({action:'start',vehicle:profile().vehicle})}).catch(()=>null);await getLocation().catch(()=>null);await pingPresence('shift_start');startHeartbeat();render();renderMap();}
function startHeartbeat(){if(heartbeat)clearInterval(heartbeat);if(shift())heartbeat=setInterval(()=>pingPresence('heartbeat'),120000)}
function updateClock(){const s=shift();if(!s){$('shiftClock').textContent='0:00';return}const sec=Math.floor((Date.now()-new Date(s.startedAt))/1000),h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60);$('shiftClock').textContent=`${h}:${String(m).padStart(2,'0')}`}
async function testCapture(){try{const p=await getLocation().catch(()=>({})),last=offers[0],idleMinutes=last?minsSince(last.captured_at):0,out=await api('/api/capture',{method:'POST',body:JSON.stringify({text:$('testText').value,...p,idleMinutes,vehicle:profile().vehicle})});alert(`${out.verdict} · ${out.parsed.merchant||'merchant?'} · ${out.rate?`$${Math.round(out.rate.dollarsPerHour)}/hr`:'rate?'}`);await refreshData()}catch(e){alert(e.message)}}
const onboardSteps=[
()=>`<div class="kicker">COURIER RADAR</div><h2>Stop guessing where the next order is.</h2><p>Radar learns the market you actually see, then tells you when to stay, widen, or leave.</p><div class="preview"><span class="eyebrow">LIVE EXAMPLE</span><strong>MOVE → PALMS</strong><p>Higher observed offer flow and a stronger next-position profile.</p></div>`,
()=>`<div class="kicker">OPTIMIZE THE RIGHT THING</div><h2>Idle time is the enemy.</h2><p>A good $/mile order does not save a dead hour. Radar weights offer arrival rate, effective $/hr, exposure time, and reposition quality.</p><div class="preview"><strong>3.8 offers/hr</strong><p>Observed market response matters more than a generic red hotspot.</p></div>`,
()=>`<div class="kicker">PERSONALIZE</div><h2>Your vehicle changes the market.</h2><p>Cars, bikes, and e-bikes should not share one dispatch model.</p><div class="choices"><button class="choice" data-vehicle="ebike">⚡ E-bike</button><button class="choice" data-vehicle="bike">🚲 Bike</button><button class="choice" data-vehicle="car">🚗 Car</button></div><div class="field"><label>Target online $ / hour</label><input id="targetInput" inputmode="decimal" value="${profile().target}"></div>`,
()=>`<div class="kicker">WHY LOCATION</div><h2>Measure the market response.</h2><p>Radar uses your position while you run a shift to measure how much online exposure each market cell receives. It does not assume Radar users equal all Uber couriers.</p><div class="trust"><b>Unknown supply still shows up.</b><p>If a cell gets lots of online exposure but few offers, Radar marks it weak whether the cause is low demand, non-Radar couriers, or Uber dispatch behavior.</p></div>`,
()=>`<div class="kicker">ZERO-FRICTION CAPTURE</div><h2>Your phone becomes the sensor.</h2><p>Double Back Tap captures the offer screenshot/OCR. Triple Back Tap marks the latest offer accepted. No spreadsheet while riding.</p><div class="trust"><b>Private alpha</b><p>After deployment, paste your capture token once in the setup section.</p></div>`,
()=>`<div class="kicker">READY</div><h2>Your first shift trains Radar.</h2><p>Personal cells work with one driver. Shared network cells appear only after enough distinct couriers contribute, so we do not expose individual driver locations.</p><div class="preview"><strong>START WITH REAL OFFERS</strong><p>The first useful dataset is tonight's actual market.</p></div>`
];
function showOnboard(){const root=$('onboarding');if(localStorage.getItem(ONBOARD_KEY)){root.classList.add('hidden');return}root.classList.remove('hidden');renderOnboard()}
function renderOnboard(){const p=profile();$('onboardBody').innerHTML=onboardSteps[onboardStep]();$('dots').innerHTML=onboardSteps.map((_,i)=>`<i class="${i===onboardStep?'active':''}"></i>`).join('');$('backBtn').classList.toggle('hidden',onboardStep===0);$('skipBtn').classList.toggle('hidden',onboardStep===onboardSteps.length-1);$('nextBtn').textContent=onboardStep===onboardSteps.length-1?'Launch Radar':'Continue';document.querySelectorAll('[data-vehicle]').forEach(btn=>{btn.classList.toggle('selected',btn.dataset.vehicle===p.vehicle);btn.onclick=()=>{saveProfile({vehicle:btn.dataset.vehicle});renderOnboard()}});const t=$('targetInput');if(t)t.onchange=()=>saveProfile({target:Math.max(15,Math.min(100,Number(t.value)||35))});}
function nextOnboard(){if(onboardStep<onboardSteps.length-1){onboardStep++;renderOnboard()}else{localStorage.setItem(ONBOARD_KEY,'1');$('onboarding').classList.add('hidden');getLocation().catch(()=>null).finally(()=>{render();renderMap()})}}
$('saveRiderSettings').onclick=()=>saveRiderSettings().then(()=>refreshData()).catch(e=>alert(e.message));document.querySelectorAll('[data-speed-level]').forEach(btn=>btn.onclick=()=>saveRiderSettings({active_speed_level:btn.dataset.speedLevel}).catch(e=>alert(e.message)));$('nextBtn').onclick=nextOnboard;$('backBtn').onclick=()=>{if(onboardStep>0){onboardStep--;renderOnboard()}};$('skipBtn').onclick=()=>{localStorage.setItem(ONBOARD_KEY,'1');$('onboarding').classList.add('hidden')};$('saveToken').onclick=async()=>{const value=$('token').value.trim();if(!value){alert('Paste your capture token first.');return}localStorage.setItem(TOKEN_KEY,value);$('saveToken').textContent='Saved ✓';$('saveToken').disabled=true;try{await refreshData();$('saveToken').textContent='Saved ✓'}catch{}setTimeout(()=>{$('saveToken').textContent='Save token';$('saveToken').disabled=false},1800)};$('testBtn').onclick=testCapture;$('acceptBtn').onclick=()=>mark('accepted');$('rejectBtn').onclick=()=>mark('rejected');$('shiftBtn').onclick=toggleShift;$('locateBtn').onclick=async()=>{await getLocation();await centerRadarMap(position);await renderMap()};if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){pingPresence('visible');refreshData()}});setInterval(()=>{updateClock();updateServerClock()},1000);setInterval(refreshData,12000);startHeartbeat();showOnboard();getLocation().catch(()=>null).finally(()=>{refreshData();renderMap()});render();
async function importUberCsv(){const file=$('earningsFile')?.files?.[0];if(!file){$('importStatus').textContent='Choose an Uber CSV first.';return}const text=await file.text(),lines=text.split(/\r?\n/).filter(Boolean);if(lines.length<2){$('importStatus').textContent='CSV appears empty.';return}const parse=line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out};const headers=parse(lines[0]).map(x=>x.trim().toLowerCase());const amountIdx=headers.findIndex(h=>/earnings|amount|fare|payout|net/.test(h)),dateIdx=headers.findIndex(h=>/date|time/.test(h)),tripIdx=headers.findIndex(h=>/trip.*id|uuid|id/.test(h));if(amountIdx<0){$('importStatus').textContent='Could not identify an earnings/amount column.';return}const rows=[];for(const line of lines.slice(1)){const v=parse(line),amount=Number(String(v[amountIdx]||'').replace(/[$,]/g,''));if(!Number.isFinite(amount))continue;rows.push({amount,date:v[dateIdx]||new Date().toISOString(),external_id:v[tripIdx]||undefined,source:'uber_csv'})}$('importEarnings').disabled=true;$('importStatus').textContent=`Importing ${rows.length} rows…`;try{const out=await api('/api/earnings',{method:'POST',body:JSON.stringify({rows})});$('importStatus').textContent=`Imported ${out.saved} earnings rows ✓`;await refreshData()}catch(e){$('importStatus').textContent=e.message}finally{$('importEarnings').disabled=false}}
if($('importEarnings'))$('importEarnings').onclick=importUberCsv;
function setTab(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));if(name==='live')setTimeout(()=>renderMap(),80);window.scrollTo({top:0,behavior:'instant'});}
document.querySelectorAll('.nav-btn').forEach(btn=>btn.onclick=()=>setTab(btn.dataset.tab));
setInterval(()=>{const el=$('syncStatus');if(!el)return;el.classList.toggle('ok',Boolean(token()));el.textContent=token()?'SYNCED':'SETUP';},1000);
