import { initRadarMap, updateRadarMap, centerRadarMap } from './map.js';

const $=id=>document.getElementById(id),TOKEN_KEY='radar_token',PROFILE_KEY='radar_profile',SHIFT_KEY='radar_shift',ONBOARD_KEY='radar_onboard_v1';
let offers=[],position=null,network={personal:[],market:[],networkCoverage:'learning'},heartbeat=null,onboardStep=0;
const defaults={vehicle:'ebike',target:35,radius:2.5};
const profile=()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(PROFILE_KEY)||'{}')}}catch{return {...defaults}}};
const saveProfile=p=>localStorage.setItem(PROFILE_KEY,JSON.stringify({...profile(),...p}));
const token=()=>localStorage.getItem(TOKEN_KEY)||'';
const shift=()=>{try{return JSON.parse(localStorage.getItem(SHIFT_KEY)||'null')}catch{return null}};
const saveShift=v=>v?localStorage.setItem(SHIFT_KEY,JSON.stringify(v)):localStorage.removeItem(SHIFT_KEY);
const headers=()=>({'Content-Type':'application/json','x-capture-token':token()});
const money=n=>n==null?'—':`$${Number(n).toFixed(2)}`;
const minsSince=iso=>Math.max(0,(Date.now()-new Date(iso).getTime())/60000);
function blockFor(d=new Date()){const h=d.getHours()+d.getMinutes()/60;if(h>=6&&h<10.5)return'BREAKFAST';if(h>=10.5&&h<14.5)return'LUNCH';if(h>=14.5&&h<16.5)return'AFTERNOON';if(h>=16.5&&h<21)return'DINNER';if(h>=21||h<1)return'LATE';return'OFF-PEAK'}
async function api(path,opt={}){if(!token())throw new Error('Set your capture token first.');const r=await fetch(path,{...opt,headers:{...headers(),...(opt.headers||{})}}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function getLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location unavailable'));navigator.geolocation.getCurrentPosition(p=>{position={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};resolve(position)},reject,{enableHighAccuracy:true,maximumAge:45000,timeout:8000})})}
async function pingPresence(event='heartbeat'){if(!shift()||!token())return;try{const p=await getLocation();await api('/api/presence',{method:'POST',body:JSON.stringify({...p,event,vehicle:profile().vehicle})});}catch{}}
function recent(minutes=60){const cut=Date.now()-minutes*60000;return offers.filter(o=>new Date(o.captured_at).getTime()>=cut)}
function effectiveDph(o){if(!(Number(o?.payout)>0))return null;const eta=Number(o.eta_minutes)||((Number(o.miles)||0)/11.5*60+5),shop=o.is_shop?Math.max(8,Math.min(25,(Number(o.item_count)||6)*1.2)):0;return Number(o.payout)/(eta+shop+5)*60}
function median(arr){const a=arr.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function bestCell(){const cells=[...(network.market?.length?network.market:network.personal||[])];return cells.sort((a,b)=>(b.properties?.score||0)-(a.properties?.score||0))[0]||null}
function recommendation(){const s=shift(),p=profile();if(!s)return{advice:'START A SHIFT',reason:'Radar needs online exposure and captured offers before it can estimate opportunity.',radius:`${p.radius.toFixed(1)} mi`,confidence:'LEARNING'};const last=offers[0],idle=last?minsSince(last.captured_at):minsSince(s.startedAt),best=bestCell(),conf=best?.properties?.confidence||0;if(idle<8)return{advice:'STAY',reason:`Fresh offer ${Math.round(idle)}m ago. Keep the tight ${p.vehicle} radius while flow is alive.`,radius:`${p.radius.toFixed(1)} mi`,confidence:conf>.6?'HIGH':'LEARNING'};if(idle<15)return{advice:'WIDEN',reason:`${Math.round(idle)} idle minutes. Allow a slightly longer order only if its effective rate still clears your target.`,radius:`${Math.max(p.radius,3.5).toFixed(1)} mi`,confidence:conf>.45?'MED':'LEARNING'};if(best)return{advice:`MOVE → ${(best.properties.label||'BEST CELL').toUpperCase()}`,reason:`${Math.round(idle)} idle minutes. Best learned cell is scoring ${best.properties.score}/100 from observed market response.`,radius:'4–5 mi escape',confidence:conf>.65?'HIGH':'MED'};return{advice:'ESCAPE MODE',reason:`${Math.round(idle)} idle minutes. Relocate once toward dense merchants or accept a longer order only when it improves your next position.`,radius:'4–5 mi escape',confidence:'LEARNING'};}
async function refreshData(){if(!token()){render();return;}try{const p=profile();const[f,n]=await Promise.all([api('/api/feed?hours=168'),api(`/api/network?hours=168&vehicle=${encodeURIComponent(p.vehicle)}&target=${p.target}`)]);offers=f.offers||[];network=n||network;}catch(e){console.warn(e)}render();renderMap();}
async function renderMap(){try{await initRadarMap();const shared=network.market?.length?network.market:null,features=shared||network.personal||[];await updateRadarMap({features,position,fit:false});$('networkBadge').textContent=shared?'NETWORK':'PERSONAL';$('networkBadge').classList.toggle('live',Boolean(shared));$('mapStatus').textContent=features.length?`${features.length} ${shared?'shared':'personal'} opportunity cell${features.length===1?'':'s'} · score uses offer flow, payout quality, recency, and confidence.`:'Capture offers while online. Unknown Uber supply is inferred from the market response you observe: offers per online exposure-hour.';}catch(e){$('mapStatus').textContent=`Map unavailable: ${e.message}`}}
function render(){const s=shift(),p=profile(),rec=recommendation(),last=offers[0];$('blockBadge').textContent=s?blockFor():'OFF';$('blockBadge').classList.toggle('live',!!s);$('advice').textContent=rec.advice;$('reason').textContent=rec.reason;$('radius').textContent=rec.radius;$('confidence').textContent=rec.confidence;$('targetMetric').textContent=`$${p.target}`;$('zone').textContent=last?.zone||'—';const idle=s?(last?minsSince(last.captured_at):minsSince(s.startedAt)):null;$('idle').textContent=idle==null?'—':`${Math.round(idle)}m`;const r=recent(60);$('pingsHr').textContent=r.length?r.length.toFixed(1):'—';const md=median(r.map(effectiveDph));$('offerDph').textContent=md?`$${Math.round(md)}`:'—';const decisions=offers.filter(o=>['accepted','completed','rejected'].includes(o.state)),taken=decisions.filter(o=>['accepted','completed'].includes(o.state)).length;$('takeRate').textContent=decisions.length?`${Math.round(taken/decisions.length*100)}%`:'—';if(last){$('lastMerchant').textContent=last.merchant||'Unknown merchant';$('lastPay').textContent=money(last.payout);$('lastMiles').textContent=last.miles?`${Number(last.miles).toFixed(1)} mi`:'—';$('lastEta').textContent=last.eta_minutes?`${last.eta_minutes}m`:'—';const d=effectiveDph(last),idleNow=s?(last?minsSince(last.captured_at):minsSince(s.startedAt)):0,mode=idleNow>=15?'escape':idleNow>=8?'slow':'normal',factor=mode==='escape'?.62:mode==='slow'?.72:.80,borderFactor=Math.max(.50,factor-.10),v=d>=p.target*factor?'TAKE':d>=p.target*borderFactor?'BORDERLINE':'SKIP';$('lastVerdict').textContent=d?`${v} · $${Math.round(d)}/h`:v;$('lastVerdict').className=`pill ${v.toLowerCase()}`}$('shiftBtn').textContent=s?'End shift':'Start shift';$('token').value=token();updateClock();}
async function mark(state){try{await api('/api/action',{method:'POST',body:JSON.stringify({state})});await refreshData()}catch(e){alert(e.message)}}
async function toggleShift(){if(shift()){await pingPresence('shift_end');saveShift(null);if(heartbeat)clearInterval(heartbeat);heartbeat=null;render();return}saveShift({startedAt:new Date().toISOString()});await getLocation().catch(()=>null);await pingPresence('shift_start');startHeartbeat();render();renderMap();}
function startHeartbeat(){if(heartbeat)clearInterval(heartbeat);if(shift())heartbeat=setInterval(()=>pingPresence('heartbeat'),120000)}
function updateClock(){const s=shift();if(!s){$('shiftClock').textContent='0:00';return}const sec=Math.floor((Date.now()-new Date(s.startedAt))/1000),h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60);$('shiftClock').textContent=`${h}:${String(m).padStart(2,'0')}`}
async function testCapture(){try{const p=await getLocation().catch(()=>({})),last=offers[0],idleMinutes=last?minsSince(last.captured_at):0,out=await api('/api/capture',{method:'POST',body:JSON.stringify({text:$('testText').value,...p,idleMinutes,vehicle:profile().vehicle})});alert(`${out.verdict} · ${out.parsed.merchant||'merchant?'} · ${out.rate?`$${Math.round(out.rate.dollarsPerHour)}/hr`:'rate?'}`);await refreshData()}catch(e){alert(e.message)}}
const onboardSteps=[
()=>`<div class="kicker">COURIER RADAR</div><h2>Stop guessing where the next order is.</h2><p>Radar learns the market you actually see, then tells you when to stay, widen, or leave.</p><div class="preview"><span class="eyebrow">LIVE EXAMPLE</span><strong>MOVE → PALMS</strong><p>Higher observed offer flow and a stronger next-position profile.</p></div>`,
()=>`<div class="kicker">OPTIMIZE THE RIGHT THING</div><h2>Idle time is the enemy.</h2><p>A good $/mile order does not save a dead hour. Radar weights offer arrival rate, effective $/hr, exposure time, and reposition quality.</p><div class="preview"><strong>3.8 offers/hr</strong><p>Observed market response matters more than a generic red hotspot.</p></div>`,
()=>`<div class="kicker">PERSONALIZE</div><h2>Your vehicle changes the market.</h2><p>Cars, bikes, and e-bikes should not share one dispatch model.</p><div class="choices"><button class="choice" data-vehicle="ebike">⚡ E-bike</button><button class="choice" data-vehicle="bike">🚲 Bike</button><button class="choice" data-vehicle="car">🚗 Car</button></div><div class="field"><label>Target online $ / hour</label><input id="targetInput" inputmode="decimal" value="${profile().target}"></div>`,
()=>`<div class="kicker">WHY LOCATION</div><h2>Measure the market response.</h2><p>Radar uses your position while you run a shift to measure how much online exposure each market cell receives. It does not assume Radar users equal all Uber couriers.</p><div class="trust"><b>Unknown supply still shows up.</b><p>If a cell gets lots of online exposure but few offers, Radar marks it weak whether the cause is low demand, non-Radar couriers, or Uber dispatch behavior.</p></div>`,
()=>`<div class="kicker">ZERO-FRICTION CAPTURE</div><h2>Your phone becomes the sensor.</h2><p>Double Back Tap captures the offer screenshot/OCR. Triple Back Tap marks the latest offer accepted. No spreadsheet while riding.</p><div class="trust"><b>Private alpha</b><p>After deployment, paste your capture token once in the setup section.</p></div>`,
()=>`<div class="kicker">READY</div><h2>Your first shift trains Radar.</h2><p>Personal cells work with one driver. Shared network cells appear only after enough distinct couriers contribute, so we do not expose individual driver locations.</p><div class="preview"><strong>START WITH REAL OFFERS</strong><p>The first useful dataset is tonight's actual market.</p></div>`
];
function showOnboard(){const root=$('onboarding');if(localStorage.getItem(ONBOARD_KEY)){root.classList.add('hidden');return}root.classList.remove('hidden');renderOnboard()}
function renderOnboard(){const p=profile();$('onboardBody').innerHTML=onboardSteps[onboardStep]();$('dots').innerHTML=onboardSteps.map((_,i)=>`<i class="${i===onboardStep?'active':''}"></i>`).join('');$('backBtn').classList.toggle('hidden',onboardStep===0);$('skipBtn').classList.toggle('hidden',onboardStep===onboardSteps.length-1);$('nextBtn').textContent=onboardStep===onboardSteps.length-1?'Launch Radar':'Continue';document.querySelectorAll('[data-vehicle]').forEach(btn=>{btn.classList.toggle('selected',btn.dataset.vehicle===p.vehicle);btn.onclick=()=>{saveProfile({vehicle:btn.dataset.vehicle});renderOnboard()}});const t=$('targetInput');if(t)t.onchange=()=>saveProfile({target:Math.max(15,Math.min(100,Number(t.value)||35))});}
function nextOnboard(){if(onboardStep<onboardSteps.length-1){onboardStep++;renderOnboard()}else{localStorage.setItem(ONBOARD_KEY,'1');$('onboarding').classList.add('hidden');getLocation().catch(()=>null).finally(()=>{render();renderMap()})}}
$('nextBtn').onclick=nextOnboard;$('backBtn').onclick=()=>{if(onboardStep>0){onboardStep--;renderOnboard()}};$('skipBtn').onclick=()=>{localStorage.setItem(ONBOARD_KEY,'1');$('onboarding').classList.add('hidden')};$('saveToken').onclick=async()=>{const value=$('token').value.trim();if(!value){alert('Paste your capture token first.');return}localStorage.setItem(TOKEN_KEY,value);$('saveToken').textContent='Saved ✓';$('saveToken').disabled=true;try{await refreshData();$('saveToken').textContent='Saved ✓'}catch{}setTimeout(()=>{$('saveToken').textContent='Save token';$('saveToken').disabled=false},1800)};$('testBtn').onclick=testCapture;$('acceptBtn').onclick=()=>mark('accepted');$('rejectBtn').onclick=()=>mark('rejected');$('shiftBtn').onclick=toggleShift;$('locateBtn').onclick=async()=>{await getLocation();await centerRadarMap(position);await renderMap()};if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){pingPresence('visible');refreshData()}});setInterval(updateClock,30000);setInterval(refreshData,60000);startHeartbeat();showOnboard();getLocation().catch(()=>null).finally(()=>{refreshData();renderMap()});render();