export const DEFAULT_TIMEZONE = 'America/Los_Angeles';
const EARTH_R = 6378137;
export function normalizeVehicle(value='ebike'){const v=String(value||'').toLowerCase();return ['bike','ebike','car'].includes(v)?v:'ebike';}
export function cellResolutionForVehicle(vehicle='ebike'){return normalizeVehicle(vehicle)==='car'?8:9;}
export const h3ResolutionForVehicle=cellResolutionForVehicle;
function cellSizeMeters(vehicle='ebike'){const v=normalizeVehicle(vehicle);return v==='car'?560:v==='bike'?330:360;}
function project(lat,lng){const x=EARTH_R*Number(lng)*Math.PI/180;const clamped=Math.max(-85,Math.min(85,Number(lat)));const y=EARTH_R*Math.log(Math.tan(Math.PI/4+clamped*Math.PI/360));return[x,y];}
function unproject(x,y){const lng=x/EARTH_R*180/Math.PI;const lat=(2*Math.atan(Math.exp(y/EARTH_R))-Math.PI/2)*180/Math.PI;return[lat,lng];}
function cubeRound(q,r){let x=q,z=r,y=-x-z;let rx=Math.round(x),ry=Math.round(y),rz=Math.round(z);const dx=Math.abs(rx-x),dy=Math.abs(ry-y),dz=Math.abs(rz-z);if(dx>dy&&dx>dz)rx=-ry-rz;else if(dy>dz)ry=-rx-rz;else rz=-rx-ry;return[rx,rz];}
function axialCenter(q,r,size){return[size*Math.sqrt(3)*(q+r/2),size*1.5*r];}
export function timeBlockForDate(input,timeZone=DEFAULT_TIMEZONE){const date=input instanceof Date?input:new Date(input);const parts=new Intl.DateTimeFormat('en-US',{timeZone,hour12:false,hour:'2-digit',minute:'2-digit'}).formatToParts(date);const hour=Number(parts.find(p=>p.type==='hour')?.value||0),minute=Number(parts.find(p=>p.type==='minute')?.value||0),h=hour+minute/60;if(h>=6&&h<10.5)return'BREAKFAST';if(h>=10.5&&h<14.5)return'LUNCH';if(h>=14.5&&h<16.5)return'AFTERNOON';if(h>=16.5&&h<21)return'DINNER';if(h>=21||h<1)return'LATE';return'OFF-PEAK';}
export function marketCellFor(lat,lng,vehicle='ebike'){if(!Number.isFinite(Number(lat))||!Number.isFinite(Number(lng)))return null;const size=cellSizeMeters(vehicle),[x,y]=project(lat,lng),q=(Math.sqrt(3)/3*x-1/3*y)/size,r=(2/3*y)/size,[rq,rr]=cubeRound(q,r);return `r${cellResolutionForVehicle(vehicle)}:${rq}:${rr}`;}
function parseCell(cell){const m=/^r(\d+):(-?\d+):(-?\d+)$/.exec(String(cell||''));return m?{resolution:Number(m[1]),q:Number(m[2]),r:Number(m[3])}:null;}
function vehicleForResolution(res){return Number(res)<=8?'car':'ebike';}
export function cellFeature(cell,properties={}){const parsed=parseCell(cell);if(!parsed)return null;const size=cellSizeMeters(vehicleForResolution(parsed.resolution)),[cx,cy]=axialCenter(parsed.q,parsed.r,size),ring=[];for(let i=0;i<6;i++){const angle=(30+60*i)*Math.PI/180,[lat,lng]=unproject(cx+size*Math.cos(angle),cy+size*Math.sin(angle));ring.push([lng,lat]);}ring.push(ring[0]);const[centerLat,centerLng]=unproject(cx,cy);return{type:'Feature',properties:{cell,centerLat,centerLng,...properties},geometry:{type:'Polygon',coordinates:[ring]}};}
export function effectiveOfferDph(row){const payout=Number(row?.payout);if(!(payout>0))return null;const miles=Number(row?.miles)||0,eta=Number(row?.eta_minutes)||((miles/11.5)*60+5),shop=row?.is_shop?Math.max(8,Math.min(25,(Number(row?.item_count)||6)*1.2)):0;return payout/Math.max(1,eta+shop+5)*60;}
export function median(values=[]){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
export function buildOpportunityCells({offers=[],presence=[],driverId=null,vehicle='ebike',timeBlock=null,targetDph=35,timeZone=DEFAULT_TIMEZONE,now=new Date(),personalOnly=false}={}){const v=normalizeVehicle(vehicle),resolution=cellResolutionForVehicle(v),block=timeBlock||timeBlockForDate(now,timeZone),groups=new Map(),activeByCell=new Map(),exposureByCell=new Map(),activeCutoff=now.getTime()-12*60_000,presenceStreams=new Map();
for(const p of presence){if(normalizeVehicle(p.vehicle||'ebike')!==v||timeBlockForDate(p.captured_at,timeZone)!==block)continue;const captured=new Date(p.captured_at).getTime();if(!Number.isFinite(captured))continue;const cell=p.market_cell||p.h3_cell||marketCellFor(p.lat,p.lng,v);if(!cell)continue;const id=p.driver_id||'anonymous';if(captured>=activeCutoff){if(!activeByCell.has(cell))activeByCell.set(cell,new Set());activeByCell.get(cell).add(id);}const key=`${id}|${cell}`;if(!presenceStreams.has(key))presenceStreams.set(key,[]);presenceStreams.get(key).push(captured);}
for(const[key,times]of presenceStreams){const cell=key.slice(key.indexOf('|')+1),windows=times.sort((a,b)=>a-b).map(t=>[t,t+2.5*60_000]);let totalMs=0,cur=null;for(const w of windows){if(!cur){cur=[...w];continue;}if(w[0]<=cur[1])cur[1]=Math.max(cur[1],w[1]);else{totalMs+=cur[1]-cur[0];cur=[...w];}}if(cur)totalMs+=cur[1]-cur[0];exposureByCell.set(cell,(exposureByCell.get(cell)||0)+totalMs/3_600_000);}
for(const row of offers){if(personalOnly&&driverId&&row.driver_id!==driverId)continue;if(normalizeVehicle(row.vehicle||'ebike')!==v)continue;const rowBlock=row.time_block||timeBlockForDate(row.captured_at,timeZone);if(rowBlock!==block)continue;const cell=row.market_cell||row.h3_cell||marketCellFor(row.lat,row.lng,v);if(!cell)continue;if(!groups.has(cell))groups.set(cell,{cell,rows:[],drivers:new Set(),zones:new Map(),dph:[],latest:0});const g=groups.get(cell);g.rows.push(row);g.drivers.add(row.driver_id||'anonymous');const zone=row.zone||'Market cell';g.zones.set(zone,(g.zones.get(zone)||0)+1);const dph=effectiveOfferDph(row);if(Number.isFinite(dph))g.dph.push(dph);g.latest=Math.max(g.latest,new Date(row.captured_at).getTime()||0);}
const totalOffers=[...groups.values()].reduce((n,g)=>n+g.rows.length,0),totalExposure=[...exposureByCell.values()].reduce((a,b)=>a+b,0),networkPriorRate=totalExposure>0?totalOffers/totalExposure:2,priorExposureHours=.75,features=[];
for(const g of groups.values()){const distinctDrivers=Math.max(1,g.drivers.size),activeRadarCouriers=activeByCell.get(g.cell)?.size||0,exposureHours=exposureByCell.get(g.cell)||0,rawOfferRate=exposureHours>0?g.rows.length/exposureHours:null,offerRate=(g.rows.length+networkPriorRate*priorExposureHours)/(exposureHours+priorExposureHours),medDph=median(g.dph)||0,hoursOld=Math.max(0,(now.getTime()-g.latest)/3_600_000),recency=Math.exp(-hoursOld/72),rateTerm=clamp(medDph/Math.max(1,Number(targetDph)||35),0,1.5)/1.5,flowTerm=clamp(offerRate/4,0,1.5)/1.5,sampleTerm=clamp((g.rows.length/20+exposureHours/6+distinctDrivers/8)/3,0,1),radarCrowdingPenalty=1/(1+.08*Math.max(0,activeRadarCouriers-1)),score=clamp(Math.round(100*(.45*rateTerm+.38*flowTerm+.17*Math.max(recency,sampleTerm*.65))*radarCrowdingPenalty),0,100),heat=score>=70?'HOT ZONE':score>=50?'WARM ZONE':score>=30?'COOL ZONE':'DEAD ZONE',confidence=clamp((g.rows.length/20+exposureHours/5+distinctDrivers/6)/3,.08,1),label=[...g.zones.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Market cell',feature=cellFeature(g.cell,{label,vehicle:v,resolution,timeBlock:block,offers:g.rows.length,distinctDrivers,activeRadarCouriers,exposureHours:Number(exposureHours.toFixed(2)),offersPerOnlineHour:Number(offerRate.toFixed(2)),rawOffersPerOnlineHour:rawOfferRate==null?null:Number(rawOfferRate.toFixed(2)),medianDph:Number(medDph.toFixed(2)),score,heat,confidence:Number(confidence.toFixed(2)),lastSeen:g.latest?new Date(g.latest).toISOString():null});if(feature)features.push(feature);}
return features.sort((a,b)=>b.properties.score-a.properties.score);}