import { parseOfferText, effectiveOfferRate, decisionForOffer } from '../lib-parser.js';
import { cors, requireToken, dbConfigured, insert, select, patch, bodyOf, zoneFor, zoneHintFromText } from './_shared.js';
import { marketCellFor, normalizeVehicle, timeBlockForDate, DEFAULT_TIMEZONE } from '../lib-network.js';
export default async function handler(req,res){
  cors(res); if(req.method==='OPTIONS')return res.status(204).end(); if(req.method!=='POST')return res.status(405).json({error:'POST only'});
  const driverId=requireToken(req,res); if(!driverId)return;
  const body=await bodyOf(req); let settings={target_dph:Number(process.env.TARGET_DPH||35),speed_low_mph:12,speed_mid_mph:16,speed_high_mph:20,active_speed_level:'high',service_overhead_minutes:4.5}; if(dbConfigured()){try{const rows=await select(`driver_settings?driver_id=eq.${driverId}&limit=1&select=*`);if(rows?.[0])settings={...settings,...rows[0]}}catch{}} const parsed=parseOfferText(body.text||body.rawText||''),lat=Number(body.lat),lng=Number(body.lng),zone=body.zone||zoneFor(lat,lng),vehicle=normalizeVehicle(body.vehicle||'ebike'),timeZone=String(body.timeZone||body.tz||DEFAULT_TIMEZONE).slice(0,80),timeBlock=String(body.timeBlock||timeBlockForDate(new Date(),timeZone)).toUpperCase(),marketCell=marketCellFor(lat,lng,vehicle),idleMinutes=Number(body.idleMinutes||0),mode=idleMinutes>=15?'escape':idleMinutes>=8?'slow':'normal',rate=effectiveOfferRate({...parsed,mode}),dropoffText=String(body.dropoffText||body.destinationText||parsed.destinationText||'').trim()||null,dropoffLat=Number(body.dropoffLat),dropoffLng=Number(body.dropoffLng),dropoffZone=body.dropoffZone||(Number.isFinite(dropoffLat)&&Number.isFinite(dropoffLng)?zoneFor(dropoffLat,dropoffLng):zoneHintFromText(dropoffText)),dropoffMarketCell=marketCellFor(dropoffLat,dropoffLng,vehicle),destinationSource=dropoffMarketCell?'coordinates':dropoffZone?'text_hint':'unknown',destinationConfidence=dropoffMarketCell?.95:dropoffZone?.6:0,speedLevel=['low','mid','high'].includes(settings.active_speed_level)?settings.active_speed_level:'high',speedMph=Number(settings[`speed_${speedLevel}_mph`]||20),routeMiles=Number(parsed.miles),radarEtaMinutes=Number.isFinite(routeMiles)&&routeMiles>0?Math.max(1,(routeMiles/Math.max(3,speedMph))*60+Number(settings.service_overhead_minutes||0)):parsed.etaMinutes;
  const row={driver_id:driverId,source:body.source||'uber_eats',captured_at:new Date().toISOString(),payout:parsed.payout,miles:parsed.miles,eta_minutes:parsed.etaMinutes,merchant:parsed.merchant,is_shop:parsed.isShop,item_count:parsed.itemCount,parser_confidence:parsed.confidence,raw_text:parsed.rawText,lat:Number.isFinite(lat)?lat:null,lng:Number.isFinite(lng)?lng:null,zone,vehicle,time_block:timeBlock,market_cell:marketCell,dropoff_text:dropoffText,dropoff_lat:Number.isFinite(dropoffLat)?dropoffLat:null,dropoff_lng:Number.isFinite(dropoffLng)?dropoffLng:null,dropoff_zone:dropoffZone,dropoff_market_cell:dropoffMarketCell,destination_source:destinationSource,destination_confidence:destinationConfidence,radar_eta_minutes:Number.isFinite(radarEtaMinutes)?Number(radarEtaMinutes.toFixed(2)):null,speed_mph:speedMph,speed_level:speedLevel,target_dph:Number(settings.target_dph||35),state:'observed'};
  let saved=null;
  if(dbConfigured()){
    try{
      const prior=await select(`offers?driver_id=eq.${driverId}&order=captured_at.desc&limit=1&select=id,state`);
      if(prior?.[0]?.state==='observed'){
        await patch(`offers?id=eq.${prior[0].id}&driver_id=eq.${driverId}`,{state:'passed'});
        await insert('offer_events',{offer_id:prior[0].id,driver_id:driverId,event:'passed',captured_at:new Date().toISOString(),lat:Number.isFinite(lat)?lat:null,lng:Number.isFinite(lng)?lng:null,zone,market_cell:marketCell});
      }
      saved=await insert('offers',row);
      if(saved?.[0]?.id)await insert('offer_events',{offer_id:saved[0].id,driver_id:driverId,event:'observed',captured_at:row.captured_at,lat:row.lat,lng:row.lng,zone:row.zone,market_cell:row.market_cell});
    }catch(error){return res.status(500).json({error:error.message,parsed,rate})}
  }
  const target=Number(settings.target_dph||35),radarRate=parsed.payout>0&&Number.isFinite(radarEtaMinutes)?{effectiveMinutes:Number(radarEtaMinutes.toFixed(1)),dollarsPerHour:Number((parsed.payout/radarEtaMinutes*60).toFixed(2))}:rate,decision=decisionForOffer({dollarsPerHour:radarRate?.dollarsPerHour,target,mode}),verdict=decision.verdict;
  return res.status(200).json({ok:true,persisted:Boolean(saved),id:saved?.[0]?.id||null,parsed,rate:radarRate,uberEtaMinutes:parsed.etaMinutes,radarEtaMinutes:Number.isFinite(radarEtaMinutes)?Number(radarEtaMinutes.toFixed(1)):null,speedMph,speedLevel,decision,verdict,zone,vehicle,timeBlock,marketCell,mode,destination:{text:dropoffText,lat:Number.isFinite(dropoffLat)?dropoffLat:null,lng:Number.isFinite(dropoffLng)?dropoffLng:null,zone:dropoffZone,marketCell:dropoffMarketCell,source:destinationSource,confidence:destinationConfidence}});
}