import { cors,requireToken,dbConfigured,select } from './_shared.js';
import { timeBlockForDate,DEFAULT_TIMEZONE } from '../lib-network.js';
const rad=x=>x*Math.PI/180,dist=(a,b,c,d)=>{const R=3958.8,p1=rad(a),p2=rad(c),dp=rad(c-a),dl=rad(d-b),q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const blockWeight=(block,tags={})=>{const amenity=tags.amenity||'',name=String(tags.name||'').toLowerCase();if(block==='LATE')return amenity==='fast_food'||['bar','pub','food_court'].includes(amenity)||/pizza|taco|burger|chicken|ramen|kebab|diner|24/.test(name)?1.35:1;if(block==='BREAKFAST')return ['cafe','fast_food'].includes(amenity)||/coffee|breakfast|donut|bagel|bakery/.test(name)?1.25:1;return amenity==='restaurant'?1.15:1};
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='GET')return res.status(405).json({error:'GET only'});const driverId=requireToken(req,res);if(!driverId)return;const lat=Number(req.query?.lat),lng=Number(req.query?.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return res.status(400).json({error:'lat/lng required'});const tz=String(req.query?.tz||DEFAULT_TIMEZONE),block=String(req.query?.block||timeBlockForDate(new Date(),tz)).toUpperCase(),radius=Math.max(3000,Math.min(20000,Number(req.query?.radius||14000))),since=new Date(Date.now()-45*86400000).toISOString();try{
 const q='[out:json][timeout:18];(node[amenity~"restaurant|fast_food|cafe|food_court|bar|pub"](around:'+radius+','+lat+','+lng+');way[amenity~"restaurant|fast_food|cafe|food_court|bar|pub"](around:'+radius+','+lat+','+lng+'););out center tags;';
 const [osm,offers]=await Promise.all([fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','user-agent':'CourierRadar/1.0'},body:'data='+encodeURIComponent(q),signal:AbortSignal.timeout(19000)}).then(r=>r.ok?r.json():{elements:[]}).catch(()=>({elements:[]})),dbConfigured()?select('offers?driver_id=eq.'+driverId+'&captured_at=gte.'+encodeURIComponent(since)+'&order=captured_at.desc&limit=2000&select=captured_at,payout,final_payout,lat,lng,state,time_block,merchant').catch(()=>[]):Promise.resolve([])]);
 const groups=new Map();for(const e of osm.elements||[]){const y=Number(e.lat??e.center?.lat),x=Number(e.lon??e.center?.lon);if(!Number.isFinite(y)||!Number.isFinite(x))continue;const gy=Math.round(y/.012)*.012,gx=Math.round(x/.012)*.012,key=gy.toFixed(3)+','+gx.toFixed(3),g=groups.get(key)||{lat:gy,lng:gx,venues:0,weighted:0,names:[]};g.venues++;g.weighted+=blockWeight(block,e.tags);if(e.tags?.name&&g.names.length<4)g.names.push(e.tags.name);groups.set(key,g)}
 const candidates=[...groups.values()].filter(g=>g.venues>=3).map(g=>{const personal=(offers||[]).filter(o=>Number.isFinite(Number(o.lat))&&Number.isFinite(Number(o.lng))&&dist(g.lat,g.lng,Number(o.lat),Number(o.lng))<=.85&&String(o.time_block||'').toUpperCase()===block),completed=personal.filter(o=>['delivered','completed'].includes(o.state)),avgPayout=completed.length?completed.reduce((a,o)=>a+Number(o.final_payout??o.payout??0),0)/completed.length:0,distance=dist(lat,lng,g.lat,g.lng),external=Math.min(100,g.weighted*4),history=Math.min(100,personal.length*12+completed.length*8+avgPayout*1.5),confidence=Math.min(1,.25+personal.length*.08),score=external*.55+history*.35+Math.max(0,10-distance*.7);return {...g,distanceMiles:Number(distance.toFixed(1)),personalOffers:personal.length,completed:completed.length,avgPayout:Number(avgPayout.toFixed(2)),externalScore:Number(external.toFixed(0)),historyScore:Number(history.toFixed(0)),confidence:Number(confidence.toFixed(2)),score:Number(score.toFixed(1))}}).sort((a,b)=>b.score-a.score).slice(0,6);
 return res.status(200).json({block,source:'OpenStreetMap venue density + your Radar history',liveBusyness:false,externalCoverage:(osm.elements||[]).length,candidates});
 }catch(e){return res.status(500).json({error:e.message})}}
