import { cors,requireToken,dbConfigured,select,upsert } from './_shared.js';
import { timeBlockForDate,DEFAULT_TIMEZONE } from '../lib-network.js';
const rad=x=>x*Math.PI/180,dist=(a,b,c,d)=>{const R=3958.8,p1=rad(a),p2=rad(c),dp=rad(c-a),dl=rad(d-b),q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q))};
const blockWeight=(block,tags={})=>{const amenity=tags.amenity||'',name=String(tags.name||'').toLowerCase();if(block==='LATE')return amenity==='fast_food'||['bar','pub','food_court'].includes(amenity)||/pizza|taco|burger|chicken|ramen|kebab|diner|24/.test(name)?1.35:1;if(block==='BREAKFAST')return ['cafe','fast_food'].includes(amenity)||/coffee|breakfast|donut|bagel|bakery/.test(name)?1.25:1;return amenity==='restaurant'?1.15:1};
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='GET')return res.status(405).json({error:'GET only'});const driverId=requireToken(req,res);if(!driverId)return;const lat=Number(req.query?.lat),lng=Number(req.query?.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return res.status(400).json({error:'lat/lng required'});const tz=String(req.query?.tz||DEFAULT_TIMEZONE),block=String(req.query?.block||timeBlockForDate(new Date(),tz)).toUpperCase(),radius=Math.max(3000,Math.min(20000,Number(req.query?.radius||14000))),since=new Date(Date.now()-45*86400000).toISOString();try{
 const eventKey=process.env.TICKETMASTER_API_KEY||'',now=new Date(),eventEnd=new Date(now.getTime()+8*3600000),tmParams=new URLSearchParams({apikey:eventKey,geoPoint:lat+','+lng,radius:'15',unit:'miles',startDateTime:now.toISOString().replace(/\.\d{3}Z$/,'Z'),endDateTime:eventEnd.toISOString().replace(/\.\d{3}Z$/,'Z'),size:'40',sort:'date,asc'});
 const culverBox='33.975,-118.445,34.045,-118.365';const q='[out:json][timeout:18];(node[amenity~"restaurant|fast_food|cafe|food_court|bar|pub"]('+culverBox+');way[amenity~"restaurant|fast_food|cafe|food_court|bar|pub"]('+culverBox+');relation[amenity~"restaurant|fast_food|cafe|food_court|bar|pub"]('+culverBox+'););out center tags;';
 const bestKey=process.env.BESTTIME_API_KEY_PRIVATE||'',btParams=new URLSearchParams({api_key_private:bestKey,types:'RESTAURANT,FAST_FOOD,CAFE,BAR,FOOD_AND_DRINK',lat:lat.toFixed(3),lng:lng.toFixed(3),radius:String(radius),busy_min:'35',busy_max:'100',busy_conf:'any',foot_traffic:'limited',limit:'100',page:'0',live:'true'});const [osm,offers,bestTime,eventData,cachedMerchants]=await Promise.all([fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','user-agent':'CourierRadar/1.0'},body:'data='+encodeURIComponent(q),signal:AbortSignal.timeout(19000)}).then(r=>r.ok?r.json():{elements:[]}).catch(()=>({elements:[]})),dbConfigured()?select('offers?driver_id=eq.'+driverId+'&captured_at=gte.'+encodeURIComponent(since)+'&order=captured_at.desc&limit=2000&select=captured_at,payout,final_payout,lat,lng,state,time_block,merchant').catch(()=>[]):Promise.resolve([]),bestKey?fetch('https://besttime.app/api/v1/venues/filter?'+btParams,{signal:AbortSignal.timeout(12000)}).then(r=>r.ok?r.json():null).catch(()=>null):Promise.resolve(null),eventKey?fetch('https://app.ticketmaster.com/discovery/v2/events.json?'+tmParams,{signal:AbortSignal.timeout(9000)}).then(r=>r.ok?r.json():null).catch(()=>null):Promise.resolve(null),dbConfigured()?select('restaurant_merchants?active=eq.true&order=name.asc&limit=1000').catch(()=>[]):Promise.resolve([])]);
 const merchants=[];const groups=new Map();
 // Culver v2: keep every coordinate-backed food venue returned by OSM so the client can render
 // the full restaurant field and the scorer can discover gateway clusters instead of hand-picked hotspots.
for(const e of osm.elements||[]){const y=Number(e.lat??e.center?.lat),x=Number(e.lon??e.center?.lon);if(!Number.isFinite(y)||!Number.isFinite(x))continue;if(e.tags?.name&&merchants.length<500){const t=e.tags||{},street=[t['addr:housenumber'],t['addr:street']].filter(Boolean).join(' '),address=[street,t['addr:city'],t['addr:state'],t['addr:postcode']].filter(Boolean).join(', ');merchants.push({id:'osm:'+String(e.type||'node')+':'+String(e.id),name:t.name,lat:y,lng:x,amenity:t.amenity||'food',cuisine:t.cuisine||null,address:address||null,phone:t.phone||t['contact:phone']||null,website:t.website||t['contact:website']||null,opening_hours:t.opening_hours||null,delivery:t.delivery||null,takeaway:t.takeaway||null,source:'OpenStreetMap'})}const gy=Math.round(y/.012)*.012,gx=Math.round(x/.012)*.012,key=gy.toFixed(3)+','+gx.toFixed(3),g=groups.get(key)||{lat:gy,lng:gx,venues:0,weighted:0,names:[]};g.venues++;g.weighted+=blockWeight(block,e.tags);if(e.tags?.name&&g.names.length<4)g.names.push(e.tags.name);groups.set(key,g)}
 if(!merchants.length&&cachedMerchants?.length){for(const m of cachedMerchants){const y=Number(m.lat),x=Number(m.lng);if(!Number.isFinite(y)||!Number.isFinite(x))continue;merchants.push(m);const gy=Math.round(y/.012)*.012,gx=Math.round(x/.012)*.012,key=gy.toFixed(3)+','+gx.toFixed(3),g=groups.get(key)||{lat:gy,lng:gx,venues:0,weighted:0,names:[]};g.venues++;g.weighted+=blockWeight(block,m);if(m.name&&g.names.length<4)g.names.push(m.name);groups.set(key,g)}}
 if(dbConfigured()&&merchants.length&&osm.elements?.length){const rows=merchants.map(m=>({id:m.id,name:m.name,lat:m.lat,lng:m.lng,amenity:m.amenity,cuisine:m.cuisine,address:m.address,phone:m.phone,website:m.website,opening_hours:m.opening_hours,delivery:m.delivery,takeaway:m.takeaway,source:m.source,last_seen_at:new Date().toISOString(),metadata:{market:'culver_operating_region'}}));await upsert('restaurant_merchants',rows,'id').catch(()=>null)}
 for(const v of bestTime?.venues||[]){const y=Number(v.venue_lat),x=Number(v.venue_lng);if(!Number.isFinite(y)||!Number.isFinite(x))continue;const gy=Math.round(y/.012)*.012,gx=Math.round(x/.012)*.012,key=gy.toFixed(3)+','+gx.toFixed(3),g=groups.get(key)||{lat:gy,lng:gx,venues:0,weighted:0,names:[]};const live=Number(v.venue_foot_traffic_live?.live_busyness??v.venue_foot_traffic_live??0),forecast=Array.isArray(v.day_raw)?Math.max(...v.day_raw.map(Number).filter(Number.isFinite),0):0,busy=Math.max(live,forecast);g.weighted+=Math.max(1,busy/18);g.externalBusyness=Math.max(g.externalBusyness||0,busy);if(v.venue_name&&!g.names.includes(v.venue_name)&&g.names.length<4)g.names.push(v.venue_name);groups.set(key,g)}const events=(eventData?._embedded?.events||[]).map(e=>({name:e.name||'Event',lat:Number(e._embedded?.venues?.[0]?.location?.latitude),lng:Number(e._embedded?.venues?.[0]?.location?.longitude),start:e.dates?.start?.dateTime||e.dates?.start?.localDate,venue:e._embedded?.venues?.[0]?.name||null})).filter(e=>Number.isFinite(e.lat)&&Number.isFinite(e.lng));
 const targetUtilization=.80,referenceActiveMinutes=17.5,idleBudgetMinutes=referenceActiveMinutes*(1-targetUtilization)/targetUtilization;
 const histByMerchant=new Map();for(const o of offers||[]){const k=String(o.merchant||'').trim().toLowerCase();if(!k)continue;const h=histByMerchant.get(k)||{offers:0,completed:0,payout:0};h.offers++;if(['delivered','completed'].includes(String(o.state||'').toLowerCase())){h.completed++;h.payout+=Number(o.final_payout??o.payout??0)}histByMerchant.set(k,h)}
 const qualified=o=>{const payout=Number(o.final_payout??o.payout??0),eta=Math.max(1,Number(o.eta_minutes)||Number(o.radar_eta_minutes)||30);return payout>0&&payout/eta*60>=24};
 const merchantScore=(m,g)=>{const h=histByMerchant.get(String(m.name||'').trim().toLowerCase())||{offers:0,completed:0,payout:0},d=dist(g.lat,g.lng,m.lat,m.lng),avg=h.completed?h.payout/h.completed:0,central=Math.max(0,18-d*30),time=blockWeight(block,{amenity:m.amenity,name:m.name})*16,learned=h.offers*7+h.completed*9+avg*.7;return{...m,historicalOffers:h.offers,completed:h.completed,avgPayout:Number(avg.toFixed(2)),distanceFromCenter:Number(d.toFixed(2)),gatewayScore:Number((central+time+learned).toFixed(1)),evidenceStrength:h.completed>=2?'proven':h.offers>=2?'observed':'density-only'}};
 const normalizedMerchant=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
 const observedMerchantNames=new Set((offers||[]).map(o=>normalizedMerchant(o.merchant)).filter(Boolean));
 const completedMerchantNames=new Set((offers||[]).filter(o=>['delivered','completed'].includes(String(o.state||'').toLowerCase())).map(o=>normalizedMerchant(o.merchant)).filter(Boolean));
 const candidates=[...groups.values()].filter(g=>g.venues>=3).map(g=>{const personal=(offers||[]).filter(o=>Number.isFinite(Number(o.lat))&&Number.isFinite(Number(o.lng))&&dist(g.lat,g.lng,Number(o.lat),Number(o.lng))<=.85&&String(o.time_block||'').toUpperCase()===block),completed=personal.filter(o=>['delivered','completed'].includes(o.state)),avgPayout=completed.length?completed.reduce((a,o)=>a+Number(o.final_payout??o.payout??0),0)/completed.length:0,distance=dist(lat,lng,g.lat,g.lng),external=Math.min(100,g.weighted*4),history=Math.min(100,personal.length*12+completed.length*8+avgPayout*1.5),nearEvents=events.map(e=>({...e,distance:dist(g.lat,g.lng,e.lat,e.lng)})).filter(e=>e.distance<=1.5),eventScore=Math.min(20,nearEvents.length*8),qualifiedOffers=personal.filter(qualified),exposureHours=Math.max(.25,personal.length/3),priorRate=3,priorHours=.75,lambda=(qualifiedOffers.length+priorRate*priorHours)/(exposureHours+priorHours),expectedWait=60/Math.max(.25,lambda),next5=1-Math.exp(-lambda*5/60),predictedUtil=referenceActiveMinutes/(referenceActiveMinutes+expectedWait),confidence=Math.min(1,.20+personal.length*.07+qualifiedOffers.length*.05+(nearEvents.length?0.06:0)),knownStrong=personal.length>=4&&(completed.length>=2||history>=45),zoneType=knownStrong?'known_strong':'promising',explorationBonus=knownStrong?0:Math.min(12,external*.10+eventScore*.15),locality=Math.max(0,24-distance*8),score=external*.50+history*.24+eventScore+explorationBonus+locality,pocketMerchants=merchants.filter(m=>dist(g.lat,g.lng,m.lat,m.lng)<=.72).map(m=>merchantScore(m,g)).sort((a,b)=>b.gatewayScore-a.gatewayScore),waitAt=pocketMerchants[0]||null,nearbyRestaurantCount=pocketMerchants.length,uberObservedRestaurantCount=pocketMerchants.filter(m=>observedMerchantNames.has(normalizedMerchant(m.name))).length,confirmedPickupRestaurantCount=pocketMerchants.filter(m=>completedMerchantNames.has(normalizedMerchant(m.name))).length;return {...g,waitAt,nearbyRestaurantCount,uberObservedRestaurantCount,confirmedPickupRestaurantCount,topRestaurants:pocketMerchants.slice(0,8),qualifiedOffers:qualifiedOffers.length,expectedWaitMinutes:Number(expectedWait.toFixed(1)),next5Probability:Number(next5.toFixed(3)),predictedUtilization:Number(predictedUtil.toFixed(3)),arrivalRatePerAvailableHour:Number(lambda.toFixed(2)),distanceMiles:Number(distance.toFixed(1)),personalOffers:personal.length,completed:completed.length,avgPayout:Number(avgPayout.toFixed(2)),externalScore:Number(external.toFixed(0)),historyScore:Number(history.toFixed(0)),confidence:Number(confidence.toFixed(2)),zoneType,knownStrong,explorationBonus:Number(explorationBonus.toFixed(1)),localityScore:Number(locality.toFixed(1)),eventScore,nearEvents:nearEvents.slice(0,3),score:Number(score.toFixed(1))}}).sort((a,b)=>b.score-a.score);
 const local=candidates.filter(c=>c.distanceMiles<=2.5).sort((a,b)=>b.score-a.score),nearby=candidates.filter(c=>c.distanceMiles<=4).sort((a,b)=>b.score-a.score),known=candidates.filter(c=>c.knownStrong).sort((a,b)=>b.score-a.score),promising=candidates.filter(c=>!c.knownStrong).sort((a,b)=>b.score-a.score),recommendedLocal=local[0]||nearby[0]||candidates[0]||null,recommended=recommendedLocal;
 return res.status(200).json({block,targetUtilization,referenceActiveMinutes,idleBudgetMinutes:Number(idleBudgetMinutes.toFixed(3)),merchants,recommended,knownStrong:known.slice(0,3),promising:promising.slice(0,3),eventProviderReady:Boolean(eventKey),eventsScanned:events.length,events:events.slice(0,8),localCandidates:local.slice(0,6),nearbyCandidates:nearby.slice(0,6),recommendedLocal,source:bestTime?'BestTime foot traffic + OpenStreetMap venue density + your Radar history':'OpenStreetMap venue density + your Radar history',liveBusyness:Boolean(bestTime),providerReady:Boolean(bestKey),externalCoverage:(osm.elements||[]).length,cachedMerchantCount:cachedMerchants?.length||0,merchantSource:(osm.elements||[]).length?'OpenStreetMap live':'Supabase cache',bestTimeVenues:bestTime?.venues?.length||0,candidates:candidates.slice(0,12)});
 }catch(e){return res.status(500).json({error:e.message})}}
